// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaWWw6xNPmrwDXhWEt4SNhypcBfd4-SoE',
    appId: '1:68174174052:web:c31c34b00495103d03cc71',
    messagingSenderId: '68174174052',
    projectId: 'onechargedriver',
    authDomain: 'onechargedriver.firebaseapp.com',
    storageBucket: 'onechargedriver.firebasestorage.app',
    measurementId: 'G-QD7YFM2YJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5R4G5auJKr2dF_YA9ehTwipfVjVmSlbc',
    appId: '1:68174174052:android:6201a26f02069abd03cc71',
    messagingSenderId: '68174174052',
    projectId: 'onechargedriver',
    storageBucket: 'onechargedriver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwi_47U8e5SBECeoTlNmh0W0bVEm3d3A',
    appId: '1:68174174052:ios:258ebe962cedd69b03cc71',
    messagingSenderId: '68174174052',
    projectId: 'onechargedriver',
    storageBucket: 'onechargedriver.firebasestorage.app',
    iosBundleId: 'com.example.onecharged',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwi_47U8e5SBECeoTlNmh0W0bVEm3d3A',
    appId: '1:68174174052:ios:7ca7b8c9be9c129803cc71',
    messagingSenderId: '68174174052',
    projectId: 'onechargedriver',
    storageBucket: 'onechargedriver.firebasestorage.app',
    iosBundleId: 'com.onecharge.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaWWw6xNPmrwDXhWEt4SNhypcBfd4-SoE',
    appId: '1:68174174052:web:285e42afc64c1fb403cc71',
    messagingSenderId: '68174174052',
    projectId: 'onechargedriver',
    authDomain: 'onechargedriver.firebaseapp.com',
    storageBucket: 'onechargedriver.firebasestorage.app',
    measurementId: 'G-ZBPDNKFKC0',
  );
}
